### ISSUE TITLE
Nuke this repository?

### ISSUE THREAD

**Issue by justdave** [oa-bsa/election-manager#18]
I'm not sure if there's anything in this repository that's useful to have.  Nataepu Shohpe's system (for lack of time) ended up building more and more stuff on top of the clunky hack they already had instead of ever finishing this one, and the entire thing is going to be available as a built-in module in LodgeMaster later this month.  Nothing in this repo ever got far enough to be even useful as a technology demo.  Might as well just kill this off.

**Comment by ericjsilva** [comment]
@justdave Thanks for the background context. I am in agreement with you. I will archive the repo.
